### ISSUE TITLE
Load grounding model error

### ISSUE THREAD

**Issue by convnets** [YuankaiQi/REVERIE#3]
```
Loading grounding model
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
attribute predict layer is commented
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'layers.visual_encoder.SubjectEncoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.activation.Tanh' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "tasks/REVERIE/trainFast.py", line 416, in <module>
    utilsFast.run(make_arg_parser(), train_val)
  File "/home/test/REVERIE/tasks/REVERIE/utilsFast.py", line 309, in run
    entry_function(args)
  File "tasks/REVERIE/trainFast.py", line 333, in train_val
    agent, train_env, val_envs = train_setup(args)
  File "tasks/REVERIE/trainFast.py", line 306, in train_setup
    args, vocab, train_splits, val_splits)
  File "tasks/REVERIE/trainFast.py", line 272, in make_env_and_models
    agent = make_follower(args, vocab)
  File "tasks/REVERIE/trainFast.py", line 228, in make_follower
    agent.pointer = Pointer(args)
  File "/home/test/REVERIE/tasks/REVERIE/modelFast.py", line 1433, in __init__
    self.model = self.loadmodel()
  File "/home/test/REVERIE/tasks/REVERIE/modelFast.py", line 1797, in loadmodel
    model.load_state_dict(checkpoint['model'].state_dict())
  File "/home/test/anaconda3/envs/rog_pytorch_0.4.1_cuda_9.2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for JointMatching:
        Missing key(s) in state_dict: "sub_encoder.att_fuse.1.num_batches_tracked", "sub_matching.vis_emb_fc.1.num_batches_tracked", "sub_matching.vis_emb_fc.5.num_batches_tracked", "sub_matching.lang_emb_fc.1.num_batches_tracked", "sub_matching.lang_emb_fc.5.num_batches_tracked", "loc_matching.vis_emb_fc.1.num_batches_tracked", "loc_matching.vis_emb_fc.5.num_batches_tracked", "loc_matching.lang_emb_fc.1.num_batches_tracked", "loc_matching.lang_emb_fc.5.num_batches_tracked", "rel_matching.vis_emb_fc.1.num_batches_tracked", "rel_matching.vis_emb_fc.5.num_batches_tracked", "rel_matching.lang_emb_fc.1.num_batches_tracked", "rel_matching.lang_emb_fc.5.num_batches_tracked".
```

I tried to run training but it seems that when loading the grounding model, the `JointMatching `model does not match the `mrcn_cmr_with_st.pth` file. Can you help to check whether they match or not ?

**Comment by YuankaiQi** [comment]
Try the 0.4.0 version
