### ISSUE TITLE
OpenCV Error: OpenGL API call (Can't Create A GL Device Context) in createGlContext

### ISSUE THREAD

**Issue by lyw0929** [YuankaiQi/REVERIE#5]
When I run :python tasks/REVERIE/trainFast.py
The following error occurred：

root@e99d*******:~/mount/Matterport3DSimulator# python tasks/REVERIE/trainFast.py --feedback_method sample2step --experiment_name releaseCheck

Loading image features from img_features/ResNet-152-imagenet.tsv
Writing vocab of size 1144 to tasks/REVERIE/data/train_vocab.txt
Loading REFER ...
REVERIE Batch loaded with 10466 instructions, using splits: train
Using gt-based pointer
Gtk-Message: Failed to load module "canberra-gtk-module"
OpenCV Error: OpenGL API call (Can't Create A GL Device Context) in createGlContext, file /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/highgui/src/window_gtk.cpp, line 703
Traceback (most recent call last):
  File "tasks/REVERIE/trainFast.py", line 458, in <module>
    utilsFast.run(make_arg_parser(), train_val)
  File "/root/mount/Matterport3DSimulator/tasks/REVERIE/utilsFast.py", line 309, in run
    entry_function(args)
  File "tasks/REVERIE/trainFast.py", line 368, in train_val
    agent, train_env, val_envs = train_setup(args)
  File "tasks/REVERIE/trainFast.py", line 341, in train_setup
    args, vocab, train_splits, val_splits)
  File "tasks/REVERIE/trainFast.py", line 307, in make_env_and_models
    agent = make_follower(args, vocab)
  File "tasks/REVERIE/trainFast.py", line 259, in make_follower
    agent.pointer = Pointer(args)
  File "/root/mount/Matterport3DSimulator/tasks/REVERIE/modelFast.py", line 1465, in __init__
    self.sim = self.make_sim(args.WIDTH,args.HEIGHT,args.VFOV)
  File "/root/mount/Matterport3DSimulator/tasks/REVERIE/modelFast.py", line 1498, in make_sim
    sim.init()
RuntimeError: /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/highgui/src/window_gtk.cpp:703: error: (-219) Can't Create A GL Device Context in function createGlContext

How to solve this problem？

**Comment by YuankaiQi** [comment]
We use the simulator as described here https://github.com/peteanderson80/Matterport3DSimulator/tree/v0.1. Maybe you can find some missing packages according to this instruction.
